name: Generate Blog Files

on:
  schedule:
    # Cron syntax to run every 5 minutes
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update-blog-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant write access to the repository contents

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run script to generate blogFiles.json
        run: |
          node generate_blog_files.js

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add blogFiles.json
          git commit -m 'Update blogFiles.json'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's token to authenticate