name: Generate Image List

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on
  workflow_dispatch:

jobs:
  update-blog-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant write access to the repository contents

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run script to generate images.json
        run: |
          node update_Images.js

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add blog/images.json
          git commit -m 'Update images.json'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's token to authenticate